// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/proto.proto

package Replication

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BidMessage struct {
	ClientId             int32    `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidMessage) Reset()         { *m = BidMessage{} }
func (m *BidMessage) String() string { return proto.CompactTextString(m) }
func (*BidMessage) ProtoMessage()    {}
func (*BidMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9897619deba694d0, []int{0}
}

func (m *BidMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidMessage.Unmarshal(m, b)
}
func (m *BidMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidMessage.Marshal(b, m, deterministic)
}
func (m *BidMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidMessage.Merge(m, src)
}
func (m *BidMessage) XXX_Size() int {
	return xxx_messageInfo_BidMessage.Size(m)
}
func (m *BidMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BidMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BidMessage proto.InternalMessageInfo

func (m *BidMessage) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *BidMessage) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type OutcomeMessage struct {
	ClientId             int32    `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	HighestBid           int32    `protobuf:"varint,2,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutcomeMessage) Reset()         { *m = OutcomeMessage{} }
func (m *OutcomeMessage) String() string { return proto.CompactTextString(m) }
func (*OutcomeMessage) ProtoMessage()    {}
func (*OutcomeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9897619deba694d0, []int{1}
}

func (m *OutcomeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutcomeMessage.Unmarshal(m, b)
}
func (m *OutcomeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutcomeMessage.Marshal(b, m, deterministic)
}
func (m *OutcomeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutcomeMessage.Merge(m, src)
}
func (m *OutcomeMessage) XXX_Size() int {
	return xxx_messageInfo_OutcomeMessage.Size(m)
}
func (m *OutcomeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OutcomeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OutcomeMessage proto.InternalMessageInfo

func (m *OutcomeMessage) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *OutcomeMessage) GetHighestBid() int32 {
	if m != nil {
		return m.HighestBid
	}
	return 0
}

type AckMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMessage) Reset()         { *m = AckMessage{} }
func (m *AckMessage) String() string { return proto.CompactTextString(m) }
func (*AckMessage) ProtoMessage()    {}
func (*AckMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9897619deba694d0, []int{2}
}

func (m *AckMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessage.Unmarshal(m, b)
}
func (m *AckMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessage.Marshal(b, m, deterministic)
}
func (m *AckMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessage.Merge(m, src)
}
func (m *AckMessage) XXX_Size() int {
	return xxx_messageInfo_AckMessage.Size(m)
}
func (m *AckMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessage proto.InternalMessageInfo

func (m *AckMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ReqMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMessage) Reset()         { *m = ReqMessage{} }
func (m *ReqMessage) String() string { return proto.CompactTextString(m) }
func (*ReqMessage) ProtoMessage()    {}
func (*ReqMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9897619deba694d0, []int{3}
}

func (m *ReqMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMessage.Unmarshal(m, b)
}
func (m *ReqMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMessage.Marshal(b, m, deterministic)
}
func (m *ReqMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMessage.Merge(m, src)
}
func (m *ReqMessage) XXX_Size() int {
	return xxx_messageInfo_ReqMessage.Size(m)
}
func (m *ReqMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMessage proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BidMessage)(nil), "Replication.bidMessage")
	proto.RegisterType((*OutcomeMessage)(nil), "Replication.OutcomeMessage")
	proto.RegisterType((*AckMessage)(nil), "Replication.ackMessage")
	proto.RegisterType((*ReqMessage)(nil), "Replication.reqMessage")
}

func init() {
	proto.RegisterFile("proto/proto.proto", fileDescriptor_9897619deba694d0)
}

var fileDescriptor_9897619deba694d0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xb7, 0x8a, 0x45, 0x47, 0x11, 0xcc, 0x61, 0x5d, 0x2a, 0x88, 0x04, 0x0f, 0x9e, 0x1a,
	0x54, 0x3c, 0xa8, 0x97, 0xb5, 0x37, 0xc1, 0x45, 0xe8, 0xd1, 0x5b, 0x9a, 0x86, 0x26, 0xd8, 0x26,
	0x75, 0x67, 0xf2, 0x27, 0xfc, 0xd5, 0x42, 0xa8, 0xb6, 0xf5, 0xb4, 0x97, 0x81, 0x37, 0x2f, 0xf9,
	0x1e, 0x8f, 0x81, 0xb3, 0x7e, 0xeb, 0xc9, 0x8b, 0x38, 0xf3, 0x38, 0xd9, 0x71, 0xa9, 0xfb, 0xd6,
	0x2a, 0x49, 0xd6, 0x3b, 0xbe, 0x06, 0xa8, 0x6c, 0xbd, 0xd1, 0x88, 0xb2, 0xd1, 0x2c, 0x83, 0x43,
	0xd5, 0x5a, 0xed, 0xe8, 0xb5, 0x5e, 0x25, 0x57, 0xc9, 0xcd, 0x41, 0xf9, 0xa7, 0xd9, 0x12, 0x52,
	0xd9, 0xf9, 0xe0, 0x68, 0xb5, 0x17, 0x9d, 0x41, 0xf1, 0x37, 0x38, 0x7d, 0x0f, 0xa4, 0x7c, 0xa7,
	0x77, 0xa1, 0x5c, 0x02, 0x18, 0xdb, 0x18, 0x8d, 0x54, 0xd8, 0x7a, 0x20, 0x4d, 0x36, 0xfc, 0x1a,
	0x40, 0xaa, 0xcf, 0x5f, 0xd2, 0x12, 0x52, 0x24, 0x49, 0x01, 0x23, 0xe7, 0xa8, 0x1c, 0x14, 0x3f,
	0x01, 0xd8, 0xea, 0xaf, 0xe1, 0xd5, 0xdd, 0x77, 0x02, 0xd3, 0x4e, 0xec, 0x11, 0xf6, 0x0b, 0x5b,
	0xb3, 0xf3, 0x7c, 0xb2, 0xcc, 0xc7, 0x96, 0xd9, 0xdc, 0x18, 0xe3, 0xf8, 0x82, 0xad, 0x21, 0x2d,
	0x35, 0x86, 0x96, 0xfe, 0xfd, 0x1e, 0xd3, 0xb2, 0x8b, 0x99, 0x31, 0xaf, 0xce, 0x17, 0xc5, 0xed,
	0x87, 0x30, 0x44, 0x3d, 0x3e, 0x09, 0xd1, 0x58, 0x32, 0xa1, 0xca, 0x95, 0xef, 0xc4, 0xa6, 0x25,
	0x23, 0x5e, 0x10, 0x6d, 0xe3, 0x3a, 0xed, 0xe8, 0xe1, 0x79, 0xc2, 0xa8, 0xd2, 0x78, 0x97, 0xfb,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x0d, 0x77, 0x02, 0xac, 0x01, 0x00, 0x00,
}
